# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QPushButton, QSizePolicy,
    QTimeEdit, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(950, 700)
        MainWindow.setMinimumSize(QSize(950, 700))
        MainWindow.setMaximumSize(QSize(950, 700))
        icon = QIcon()
        icon.addFile(u":/media/icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"font-family: Inter;")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Frame1 = QFrame(self.centralwidget)
        self.Frame1.setObjectName(u"Frame1")
        self.Frame1.setGeometry(QRect(9, 9, 463, 611))
        self.Frame1.setAutoFillBackground(False)
        self.Frame1.setStyleSheet(u"")
        self.Frame1.setFrameShape(QFrame.Shape.StyledPanel)
        self.Frame1.setFrameShadow(QFrame.Shadow.Raised)
        self.layoutWidget = QWidget(self.Frame1)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(21, 11, 421, 581))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.FileCount = QLabel(self.layoutWidget)
        self.FileCount.setObjectName(u"FileCount")
        font = QFont()
        font.setFamilies([u"Inter"])
        font.setPointSize(10)
        self.FileCount.setFont(font)

        self.gridLayout.addWidget(self.FileCount, 3, 0, 1, 1)

        self.txtStep1 = QLabel(self.layoutWidget)
        self.txtStep1.setObjectName(u"txtStep1")
        font1 = QFont()
        font1.setFamilies([u"Inter"])
        font1.setPointSize(13)
        self.txtStep1.setFont(font1)

        self.gridLayout.addWidget(self.txtStep1, 0, 0, 1, 1)

        self.btnClearList = QPushButton(self.layoutWidget)
        self.btnClearList.setObjectName(u"btnClearList")
        self.btnClearList.setFont(font1)
        self.btnClearList.setStyleSheet(u"")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditDelete))
        self.btnClearList.setIcon(icon1)
        self.btnClearList.setIconSize(QSize(15, 15))

        self.gridLayout.addWidget(self.btnClearList, 1, 1, 1, 1)

        self.btnAddFiles = QPushButton(self.layoutWidget)
        self.btnAddFiles.setObjectName(u"btnAddFiles")
        self.btnAddFiles.setFont(font1)
        self.btnAddFiles.setStyleSheet(u"")
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentPageSetup))
        self.btnAddFiles.setIcon(icon2)
        self.btnAddFiles.setIconSize(QSize(15, 15))

        self.gridLayout.addWidget(self.btnAddFiles, 1, 0, 1, 1)

        self.listFiles = QListWidget(self.layoutWidget)
        self.listFiles.setObjectName(u"listFiles")
        self.listFiles.setEnabled(True)
        self.listFiles.setFont(font)

        self.gridLayout.addWidget(self.listFiles, 2, 0, 1, 2)

        self.Frame2 = QFrame(self.centralwidget)
        self.Frame2.setObjectName(u"Frame2")
        self.Frame2.setGeometry(QRect(478, 9, 463, 611))
        self.Frame2.setAutoFillBackground(False)
        self.Frame2.setStyleSheet(u"")
        self.Frame2.setFrameShape(QFrame.Shape.StyledPanel)
        self.Frame2.setFrameShadow(QFrame.Shadow.Raised)
        self.Frame2.setLineWidth(1)
        self.Frame2.setMidLineWidth(0)
        self.txtStep2 = QLabel(self.Frame2)
        self.txtStep2.setObjectName(u"txtStep2")
        self.txtStep2.setGeometry(QRect(21, 15, 139, 21))
        self.txtStep2.setFont(font1)
        self.txtFormat = QLabel(self.Frame2)
        self.txtFormat.setObjectName(u"txtFormat")
        self.txtFormat.setGeometry(QRect(21, 43, 151, 21))
        self.txtFormat.setFont(font1)
        self.txtResolution = QLabel(self.Frame2)
        self.txtResolution.setObjectName(u"txtResolution")
        self.txtResolution.setGeometry(QRect(21, 145, 80, 21))
        self.txtResolution.setFont(font1)
        self.txtFPS = QLabel(self.Frame2)
        self.txtFPS.setObjectName(u"txtFPS")
        self.txtFPS.setGeometry(QRect(21, 220, 28, 21))
        self.txtFPS.setFont(font1)
        self.txtBitrate = QLabel(self.Frame2)
        self.txtBitrate.setObjectName(u"txtBitrate")
        self.txtBitrate.setGeometry(QRect(21, 295, 231, 21))
        self.txtBitrate.setFont(font1)
        self.KeepOriginal = QCheckBox(self.Frame2)
        self.KeepOriginal.setObjectName(u"KeepOriginal")
        self.KeepOriginal.setGeometry(QRect(20, 115, 160, 24))
        self.txtOutputPath = QLabel(self.Frame2)
        self.txtOutputPath.setObjectName(u"txtOutputPath")
        self.txtOutputPath.setGeometry(QRect(205, 535, 111, 19))
        self.txtOutputPath.setFont(font1)
        self.BoxFormats = QComboBox(self.Frame2)
        self.BoxFormats.addItem("")
        self.BoxFormats.addItem("")
        self.BoxFormats.addItem("")
        self.BoxFormats.addItem("")
        self.BoxFormats.setObjectName(u"BoxFormats")
        self.BoxFormats.setGeometry(QRect(21, 70, 421, 34))
        self.BoxFormats.setFont(font1)
        self.BoxFormats.setStyleSheet(u"")
        self.BoxResolutions = QComboBox(self.Frame2)
        self.BoxResolutions.addItem("")
        self.BoxResolutions.addItem("")
        self.BoxResolutions.addItem("")
        self.BoxResolutions.addItem("")
        self.BoxResolutions.addItem("")
        self.BoxResolutions.addItem("")
        self.BoxResolutions.addItem("")
        self.BoxResolutions.addItem("")
        self.BoxResolutions.addItem("")
        self.BoxResolutions.setObjectName(u"BoxResolutions")
        self.BoxResolutions.setGeometry(QRect(21, 172, 161, 34))
        self.BoxResolutions.setFont(font1)
        self.BoxResolutions.setStyleSheet(u"")
        self.btnBrowse = QPushButton(self.Frame2)
        self.btnBrowse.setObjectName(u"btnBrowse")
        self.btnBrowse.setGeometry(QRect(385, 555, 51, 41))
        self.btnBrowse.setFont(font1)
        self.btnBrowse.setStyleSheet(u"")
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.FolderOpen))
        self.btnBrowse.setIcon(icon3)
        self.btnBrowse.setIconSize(QSize(20, 20))
        self.BoxFPS = QComboBox(self.Frame2)
        self.BoxFPS.addItem("")
        self.BoxFPS.addItem("")
        self.BoxFPS.addItem("")
        self.BoxFPS.addItem("")
        self.BoxFPS.setObjectName(u"BoxFPS")
        self.BoxFPS.setGeometry(QRect(21, 247, 161, 34))
        self.BoxFPS.setFont(font1)
        self.BoxFPS.setStyleSheet(u"")
        self.BoxBitrate = QComboBox(self.Frame2)
        self.BoxBitrate.addItem("")
        self.BoxBitrate.addItem("")
        self.BoxBitrate.addItem("")
        self.BoxBitrate.addItem("")
        self.BoxBitrate.addItem("")
        self.BoxBitrate.addItem("")
        self.BoxBitrate.setObjectName(u"BoxBitrate")
        self.BoxBitrate.setGeometry(QRect(21, 321, 161, 34))
        self.BoxBitrate.setFont(font1)
        self.BoxBitrate.setStyleSheet(u"")
        self.txtX = QLabel(self.Frame2)
        self.txtX.setObjectName(u"txtX")
        self.txtX.setGeometry(QRect(320, 180, 16, 16))
        self.CropTheVideo = QCheckBox(self.Frame2)
        self.CropTheVideo.setObjectName(u"CropTheVideo")
        self.CropTheVideo.setEnabled(True)
        self.CropTheVideo.setGeometry(QRect(21, 440, 113, 24))
        self.CropTheVideo.setStyleSheet(u"")
        self.txtStart = QLabel(self.Frame2)
        self.txtStart.setObjectName(u"txtStart")
        self.txtStart.setGeometry(QRect(21, 470, 41, 16))
        self.txtStart.setFont(font1)
        self.txtEnd = QLabel(self.Frame2)
        self.txtEnd.setObjectName(u"txtEnd")
        self.txtEnd.setGeometry(QRect(235, 470, 31, 16))
        self.txtEnd.setFont(font1)
        self.timeStart = QTimeEdit(self.Frame2)
        self.timeStart.setObjectName(u"timeStart")
        self.timeStart.setEnabled(False)
        self.timeStart.setGeometry(QRect(21, 491, 181, 34))
        self.timeStart.setFont(font1)
        self.timeStart.setStyleSheet(u"")
        self.timeEnd = QTimeEdit(self.Frame2)
        self.timeEnd.setObjectName(u"timeEnd")
        self.timeEnd.setEnabled(False)
        self.timeEnd.setGeometry(QRect(230, 491, 181, 34))
        self.timeEnd.setFont(font1)
        self.timeEnd.setStyleSheet(u"")
        self.txtDash = QLabel(self.Frame2)
        self.txtDash.setObjectName(u"txtDash")
        self.txtDash.setGeometry(QRect(210, 490, 16, 30))
        font2 = QFont()
        font2.setFamilies([u"Inter"])
        font2.setPointSize(19)
        self.txtDash.setFont(font2)
        self.txtNewName = QLabel(self.Frame2)
        self.txtNewName.setObjectName(u"txtNewName")
        self.txtNewName.setGeometry(QRect(21, 535, 131, 19))
        self.txtNewName.setFont(font1)
        self.entryW = QLineEdit(self.Frame2)
        self.entryW.setObjectName(u"entryW")
        self.entryW.setGeometry(QRect(218, 172, 91, 34))
        font3 = QFont()
        font3.setFamilies([u"Inter"])
        font3.setPointSize(14)
        self.entryW.setFont(font3)
        self.entryH = QLineEdit(self.Frame2)
        self.entryH.setObjectName(u"entryH")
        self.entryH.setGeometry(QRect(338, 172, 91, 34))
        self.entryH.setFont(font3)
        self.entryFPS = QLineEdit(self.Frame2)
        self.entryFPS.setObjectName(u"entryFPS")
        self.entryFPS.setGeometry(QRect(218, 247, 211, 34))
        self.entryFPS.setFont(font3)
        self.entryBitrate = QLineEdit(self.Frame2)
        self.entryBitrate.setObjectName(u"entryBitrate")
        self.entryBitrate.setGeometry(QRect(218, 321, 211, 34))
        self.entryBitrate.setFont(font3)
        self.entryName = QLineEdit(self.Frame2)
        self.entryName.setObjectName(u"entryName")
        self.entryName.setGeometry(QRect(21, 559, 161, 34))
        self.entryName.setFont(font1)
        self.entryPath = QLineEdit(self.Frame2)
        self.entryPath.setObjectName(u"entryPath")
        self.entryPath.setGeometry(QRect(200, 559, 171, 34))
        self.entryPath.setFont(font1)
        self.entrySound = QLineEdit(self.Frame2)
        self.entrySound.setObjectName(u"entrySound")
        self.entrySound.setGeometry(QRect(218, 396, 211, 34))
        self.entrySound.setFont(font3)
        self.txtSound = QLabel(self.Frame2)
        self.txtSound.setObjectName(u"txtSound")
        self.txtSound.setGeometry(QRect(21, 370, 176, 21))
        self.txtSound.setFont(font1)
        self.BoxSound = QComboBox(self.Frame2)
        self.BoxSound.addItem("")
        self.BoxSound.addItem("")
        self.BoxSound.addItem("")
        self.BoxSound.addItem("")
        self.BoxSound.addItem("")
        self.BoxSound.setObjectName(u"BoxSound")
        self.BoxSound.setGeometry(QRect(21, 396, 161, 34))
        self.BoxSound.setFont(font1)
        self.BoxSound.setStyleSheet(u"")
        self.Frame3 = QFrame(self.centralwidget)
        self.Frame3.setObjectName(u"Frame3")
        self.Frame3.setGeometry(QRect(9, 630, 931, 61))
        self.Frame3.setStyleSheet(u"")
        self.Frame3.setFrameShape(QFrame.Shape.StyledPanel)
        self.Frame3.setFrameShadow(QFrame.Shadow.Raised)
        self.btnConvert = QPushButton(self.Frame3)
        self.btnConvert.setObjectName(u"btnConvert")
        self.btnConvert.setGeometry(QRect(740, 10, 171, 41))
        self.btnConvert.setFont(font1)
        self.btnConvert.setStyleSheet(u"")
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.SyncSynchronizing))
        self.btnConvert.setIcon(icon4)
        self.btnAbout = QPushButton(self.Frame3)
        self.btnAbout.setObjectName(u"btnAbout")
        self.btnAbout.setGeometry(QRect(690, 10, 40, 41))
        self.btnAbout.setFont(font1)
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.InsertImage))
        self.btnAbout.setIcon(icon5)
        self.txtStatus = QLabel(self.Frame3)
        self.txtStatus.setObjectName(u"txtStatus")
        self.txtStatus.setGeometry(QRect(20, 15, 651, 31))
        font4 = QFont()
        font4.setFamilies([u"Inter"])
        font4.setPointSize(11)
        self.txtStatus.setFont(font4)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(1070, 220, 421, 231))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"FFmpeg Studio v1.1.2", None))
        self.FileCount.setText(QCoreApplication.translate("MainWindow", u"0 files", None))
        self.txtStep1.setText(QCoreApplication.translate("MainWindow", u"1. Add Files", None))
        self.btnClearList.setText(QCoreApplication.translate("MainWindow", u" Clear List", None))
        self.btnAddFiles.setText(QCoreApplication.translate("MainWindow", u" Add Files", None))
        self.txtStep2.setText(QCoreApplication.translate("MainWindow", u"2. Output Settings", None))
        self.txtFormat.setText(QCoreApplication.translate("MainWindow", u"Format", None))
        self.txtResolution.setText(QCoreApplication.translate("MainWindow", u"Resolution", None))
        self.txtFPS.setText(QCoreApplication.translate("MainWindow", u"FPS", None))
        self.txtBitrate.setText(QCoreApplication.translate("MainWindow", u"Video bitrate (kbps)", None))
#if QT_CONFIG(tooltip)
        self.KeepOriginal.setToolTip(QCoreApplication.translate("MainWindow", u"Keep empty the setting you do not want to change.", None))
#endif // QT_CONFIG(tooltip)
        self.KeepOriginal.setText(QCoreApplication.translate("MainWindow", u"Keep original properties", None))
        self.txtOutputPath.setText(QCoreApplication.translate("MainWindow", u"Output Folder", None))
        self.BoxFormats.setItemText(0, QCoreApplication.translate("MainWindow", u"Original format", None))
        self.BoxFormats.setItemText(1, QCoreApplication.translate("MainWindow", u"mp4", None))
        self.BoxFormats.setItemText(2, QCoreApplication.translate("MainWindow", u"mkv", None))
        self.BoxFormats.setItemText(3, QCoreApplication.translate("MainWindow", u"mov", None))

        self.BoxResolutions.setItemText(0, QCoreApplication.translate("MainWindow", u"Custom", None))
        self.BoxResolutions.setItemText(1, QCoreApplication.translate("MainWindow", u"4K", None))
        self.BoxResolutions.setItemText(2, QCoreApplication.translate("MainWindow", u"UHD", None))
        self.BoxResolutions.setItemText(3, QCoreApplication.translate("MainWindow", u"Quad HD", None))
        self.BoxResolutions.setItemText(4, QCoreApplication.translate("MainWindow", u"2K", None))
        self.BoxResolutions.setItemText(5, QCoreApplication.translate("MainWindow", u"Full HD", None))
        self.BoxResolutions.setItemText(6, QCoreApplication.translate("MainWindow", u"HD", None))
        self.BoxResolutions.setItemText(7, QCoreApplication.translate("MainWindow", u"SVGA", None))
        self.BoxResolutions.setItemText(8, QCoreApplication.translate("MainWindow", u"VGA", None))

        self.btnBrowse.setText("")
        self.BoxFPS.setItemText(0, QCoreApplication.translate("MainWindow", u"Custom", None))
        self.BoxFPS.setItemText(1, QCoreApplication.translate("MainWindow", u"120", None))
        self.BoxFPS.setItemText(2, QCoreApplication.translate("MainWindow", u"60", None))
        self.BoxFPS.setItemText(3, QCoreApplication.translate("MainWindow", u"30", None))

        self.BoxBitrate.setItemText(0, QCoreApplication.translate("MainWindow", u"Custom", None))
        self.BoxBitrate.setItemText(1, QCoreApplication.translate("MainWindow", u"10000 kbps", None))
        self.BoxBitrate.setItemText(2, QCoreApplication.translate("MainWindow", u"5000 kbps", None))
        self.BoxBitrate.setItemText(3, QCoreApplication.translate("MainWindow", u"2000 kbps", None))
        self.BoxBitrate.setItemText(4, QCoreApplication.translate("MainWindow", u"1000 kbps", None))
        self.BoxBitrate.setItemText(5, QCoreApplication.translate("MainWindow", u"500 kbps", None))

        self.txtX.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.CropTheVideo.setText(QCoreApplication.translate("MainWindow", u"Trim by time", None))
        self.txtStart.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.txtEnd.setText(QCoreApplication.translate("MainWindow", u"End", None))
#if QT_CONFIG(tooltip)
        self.timeStart.setToolTip(QCoreApplication.translate("MainWindow", u"Format - hh:mm:ss", None))
#endif // QT_CONFIG(tooltip)
        self.timeStart.setDisplayFormat(QCoreApplication.translate("MainWindow", u"HH:mm:ss.zzz", None))
#if QT_CONFIG(tooltip)
        self.timeEnd.setToolTip(QCoreApplication.translate("MainWindow", u"Format - hh:mm:ss", None))
#endif // QT_CONFIG(tooltip)
        self.timeEnd.setDisplayFormat(QCoreApplication.translate("MainWindow", u"HH:mm:ss.zzz", None))
        self.txtDash.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.txtNewName.setText(QCoreApplication.translate("MainWindow", u"Output file name", None))
#if QT_CONFIG(tooltip)
        self.entryW.setToolTip(QCoreApplication.translate("MainWindow", u"Width. Specify it in positive integer value.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.entryH.setToolTip(QCoreApplication.translate("MainWindow", u"Height. Specify it in positive integer value.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.entryFPS.setToolTip(QCoreApplication.translate("MainWindow", u"Specify it in positive value.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.entryBitrate.setToolTip(QCoreApplication.translate("MainWindow", u"Video bitrate. Specified in kbit/s, positive integer value.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.entrySound.setToolTip(QCoreApplication.translate("MainWindow", u"Video bitrate. Specified in kbit/s, positive integer value.", None))
#endif // QT_CONFIG(tooltip)
        self.txtSound.setText(QCoreApplication.translate("MainWindow", u"Sound quality (kbps)", None))
        self.BoxSound.setItemText(0, QCoreApplication.translate("MainWindow", u"Custom", None))
        self.BoxSound.setItemText(1, QCoreApplication.translate("MainWindow", u"320 kbps", None))
        self.BoxSound.setItemText(2, QCoreApplication.translate("MainWindow", u"256 kbps", None))
        self.BoxSound.setItemText(3, QCoreApplication.translate("MainWindow", u"128 kbps", None))
        self.BoxSound.setItemText(4, QCoreApplication.translate("MainWindow", u"64 kbps", None))

#if QT_CONFIG(tooltip)
        self.btnConvert.setToolTip(QCoreApplication.translate("MainWindow", u"Convert all selected files.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btnConvert.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.btnConvert.setText(QCoreApplication.translate("MainWindow", u" Convert", None))
        self.btnAbout.setText("")
        self.txtStatus.setText(QCoreApplication.translate("MainWindow", u"STATUS LABEL", None))
    # retranslateUi

